### ISSUE TITLE
training on a custom dataset

### ISSUE THREAD

**Issue by surfingnirvana** [winfried-ripken/wise#2]
Is it possible to train my custom dataset with just a small sample size?

**Comment by winfried-ripken** [comment]
Sure!
For [parametric style transfer](https://github.com/winfried-ripken/wise#parametric-style-transfer) you would only need a pair of style and content images like for classical style transfer. Our local parameter prediction task relies on the code for [Pix2PixGAN](https://github.com/winfried-ripken/wise/tree/main/local_ppn/data) that accepts all kinds of paired image datasets. Let me know if that answered your question!

**Comment by surfingnirvana** [comment]
If i try to run the parametric style transfer i get an error:

(base) PS C:\neural\wise> python -m parameter_optimization.parametric_styletransfer --effect xdog --content experiments/source/portrait.png --style experiments/target/watercolor_portrait.jpg
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\neural\wise\parameter_optimization\parametric_styletransfer.py", line 109, in <module>
    strotss_process(args.content, args.style, effect=effect, preset=preset, cpu=args.cpu)
  File "C:\neural\wise\parameter_optimization\parametric_styletransfer.py", line 92, in strotss_process
    result = execute_style_transfer(s, t, resize_dim, device="cpu" if cpu else "cuda:0")
NameError: name 'execute_style_transfer' is not defined
